CREATE TABLE app_users (
 username VARCHAR(32) PRIMARY KEY,
 password_hash VARCHAR(100) NOT NULL
);
CREATE TABLE messages (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 client_id VARCHAR(36) NOT NULL,
 sender VARCHAR(32) NOT NULL REFERENCES app_users(username),
 recipient VARCHAR(32) NOT NULL REFERENCES app_users(username),
 ciphertext VARCHAR(65536) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
 UNIQUE(sender, client_id)
);
CREATE INDEX idx_pending ON messages(recipient, acknowledged, id);
CREATE INDEX idx_conversation ON messages(sender, recipient, id);
